name: Deploy WebSite
on:
  push:
    branches:
      - deploy-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
        working-directory: ./apps/client

      - name: Create env file
        run: |
          touch .env
          echo APP_BASE_URL=${{ vars.APP_BASE_URL }} >> .env
          echo COGNITO_REGION=${{ vars.AWS_REGION }} >> .env
          echo USER_POOL_ID=${{ vars.USER_POOL_ID }} >> .env
          echo COGNITO_CLIENT_ID=${{ vars.COGNITO_CLIENT_ID }} >> .env
          cat .env
        working-directory: ./apps/client

      - name: Build
        run: CI=false yarn build
        working-directory: ./apps/client

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: 'apps/client/build'
